### PR TITLE
Move library to the root of the repository

### PR DESCRIPTION
**Pull request by per1234**
- Allows easier installation via the Arduino IDE's **Sketch > Include Library > Add .ZIP Library** feature.
- Allows inclusion in the [Arduino Library Manager index](https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ), for even easier installation and updates.

### CODE REVIEW

**Comment by BlueAndi** [comment]
Thanks for the PR.

**Comment by BlueAndi** [comment]
@per1234 What I am doing wrong, that the new library version is not shown in the Arduino IDE? Can you have a look?

**Comment by njh** [comment]
The library.properties file in the v0.7.1 tag says `version=0.6.1`.

https://github.com/BlueAndi/vscp-arduino/blob/v0.7.1/library.properties

Probably best to delete the tag and try again.

**Comment by per1234** [comment]
@BlueAndi njh explained the issue well. You always need to remember to update the `version` value in library.properties before making a new release/tag, otherwise the Library Manager indexer job will ignore the new release, since there was already a release with the same library.properties `version` value.

**Comment by BlueAndi** [comment]
Original I saw this after creating the v0.7.1 and removed the version via github webinterface, fixed it and created it again. Looking to the releases, it is 0.7.1 in the library.properties. But as I see, somehow in the git tag it was kept.

Thanks @njh and @per1234 for pointing this out. I will recreate it again.

**Pull request merged**
